# -*- coding: utf-8 -*-
"""exercicio12_exploracao_dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18-OFR-NK20n2sdxIbVARX-lvLcifWAsN
"""

# Monta o Google Drive no Colab
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

pasta = '/content/drive/MyDrive/Bases de Dados'

# Base do ENEM (formato SAS)
enem = pd.read_sas(f'{pasta}/enem_2024_amostra_perfeita.sas7bdat', encoding='latin-1')

# Base do SUS (CSV)
sus = pd.read_csv(f'{pasta}/sus_prod_ambulatorial.csv', sep=';', encoding='latin-1')

print("ENEM:", enem.shape, "linhas x colunas")
print("SUS:", sus.shape, "linhas x colunas")

print("Colunas do ENEM:")
print(list(enem.columns))

print("Colunas do ENEM:")
for c in enem.columns:
    print(" -", c)

print("Colunas relacionadas ao exercício:\n")
for c in enem.columns:
    if any(p in c.upper() for p in ['COR', 'RACA', 'RAÇA', 'MAT', 'NOTA', 'UF', 'SG_']):
        print(" -", c)

# Diagnóstico: o que realmente tem na coluna TP_COR_RACA
print("Tipo da coluna:", enem['TP_COR_RACA'].dtype)
print("\nValores únicos:")
print(enem['TP_COR_RACA'].unique())
print("\nContagem bruta (sem mapear):")
print(enem['TP_COR_RACA'].value_counts(dropna=False))

import matplotlib.pyplot as plt

# A coluna já vem com os nomes por extenso, então é só contar
contagem = enem['TP_COR_RACA'].value_counts()

# Gráfico de barras
plt.figure(figsize=(10, 6))
contagem.plot(kind='bar', color='steelblue', edgecolor='black')

plt.title('Distribuição de Candidatos por Cor/Raça (ENEM 2024)', fontsize=14)
plt.xlabel('Cor/Raça')
plt.ylabel('Número de candidatos')
plt.xticks(rotation=45, ha='right')

# Mostra o valor no topo de cada barra (opcional, fica mais profissional)
for i, v in enumerate(contagem):
    plt.text(i, v + 200, str(v), ha='center', fontsize=9)

plt.tight_layout()
plt.show()

import pandas as pd

# --- Parte 1: filtrar alunos com nota de matemática > 680 ---
acima_680 = enem[enem['NOTA_MT_MATEMATICA'] > 680]

print(f"Total de alunos na base: {len(enem)}")
print(f"Alunos com NOTA_MT_MATEMATICA > 680: {len(acima_680)}\n")

# --- Parte 2: Tabela de Distribuição de Frequência por UF ---
# Frequência absoluta (contagem de cada UF)
freq_abs = acima_680['SG_UF_PROVA'].value_counts()

# Monta a tabela completa
tabela = pd.DataFrame({
    'Frequência Absoluta': freq_abs,
    'Frequência Relativa (%)': (freq_abs / freq_abs.sum() * 100).round(2)
})

# Frequências acumuladas
tabela['Freq. Absoluta Acumulada'] = tabela['Frequência Absoluta'].cumsum()
tabela['Freq. Relativa Acumulada (%)'] = tabela['Frequência Relativa (%)'].cumsum().round(2)

# Linha de total
tabela.loc['TOTAL'] = [
    tabela['Frequência Absoluta'].sum(),
    tabela['Frequência Relativa (%)'].sum().round(2),
    '-',
    '-'
]

tabela

# Confere as colunas da base do SUS que vamos usar
print("Colunas do SUS relacionadas ao exercício:\n")
for c in sus.columns:
    if any(p in c.upper() for p in ['VL', 'TOTAL', 'ANO', 'AIH']):
        print(" -", c)

print("\nTipo de VL_Total:", sus['VL_Total'].dtype if 'VL_Total' in sus.columns else "coluna não encontrada com esse nome exato")

# Total gasto (VL_Total) somado por ano de produção ambulatorial
gasto_por_ano = sus.groupby('Ano_Producao_Ambulatorial')['VL_Total'].sum()

print("Total gasto por ano:\n")
print(gasto_por_ano)

# Versão formatada em reais (mais legível para apresentar)
print("\n--- Formatado em R$ ---\n")
for ano, valor in gasto_por_ano.items():
    print(f"{int(ano)}: R$ {valor:,.2f}".replace(',', 'X').replace('.', ',').replace('X', '.'))